### ISSUE TITLE
Does this work for Polymer 2.x RC ??

### ISSUE THREAD

**Issue by kristianmandrup** [gertcuykens/decorators#1]

**Comment by gertcuykens** [comment]
Let me check, it's been a long time I touched this code because I tend to go full typescript / ES6 only now without polymer.

In the meantime maybe this will help too

https://gist.github.com/daflair/ccaf74520480cfb8f7979e337d905f3f

Let me know what problems you are getting specifically or maybe send PR when you have improvements but try to keep it simple.

**Comment by gertcuykens** [comment]
Updated bower.json and it is still working for me 

![image](https://cloud.githubusercontent.com/assets/863731/23634316/e279e2fc-02c9-11e7-8b34-a6029c35c44c.png)

**Comment by kristianmandrup** [comment]
Sweet :) Would be nice to make a note on compatibility in Readme.
